package model;
// Generated 2019�~5��5�� �U��10:27:07 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomerBean generated by hbm2java
 */
@Entity
@Table(name = "Customer")
public class CustomerBean implements java.io.Serializable {

	private String custid;
	private Date birth;
	private String email;
	private byte[] password;

	public CustomerBean() {
	}

	public CustomerBean(String custid) {
		this.custid = custid;
	}

	public CustomerBean(String custid, Date birth, String email, byte[] password) {
		this.custid = custid;
		this.birth = birth;
		this.email = email;
		this.password = password;
	}

	@Id

	@Column(name = "custid", nullable = false)
	public String getCustid() {
		return this.custid;
	}

	public void setCustid(String custid) {
		this.custid = custid;
	}

	@Column(name = "birth")
	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password")
	public byte[] getPassword() {
		return this.password;
	}

	public void setPassword(byte[] password) {
		this.password = password;
	}

}
