package model;
// Generated 2019�~5��5�� �U��10:27:07 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductBean generated by hbm2java
 */
@Entity
@Table(name = "Product")
public class ProductBean implements java.io.Serializable {

	private int id;
	private int expire;
	private Date make;
	private String name;
	private double price;

	public ProductBean() {
	}

	public ProductBean(int id, int expire, double price) {
		this.id = id;
		this.expire = expire;
		this.price = price;
	}

	public ProductBean(int id, int expire, Date make, String name, double price) {
		this.id = id;
		this.expire = expire;
		this.make = make;
		this.name = name;
		this.price = price;
	}

	@Id

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "expire", nullable = false)
	public int getExpire() {
		return this.expire;
	}

	public void setExpire(int expire) {
		this.expire = expire;
	}

	@Column(name = "make")
	public Date getMake() {
		return this.make;
	}

	public void setMake(Date make) {
		this.make = make;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
