package model.POJO;
// Generated 2019�~5��13�� �U��12:01:30 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityArticle generated by hbm2java
 */
@Entity
@Table(name = "activityArticle", schema = "dbo", catalog = "final")
public class ActivityArticle implements java.io.Serializable {

	private Integer articleNo;
	private Activity activity;
	private String articleTitle;
	private String article;

	public ActivityArticle() {
	}

	public ActivityArticle(Activity activity, String articleTitle, String article) {
		this.activity = activity;
		this.articleTitle = articleTitle;
		this.article = article;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "articleNo", unique = true, nullable = false)
	public Integer getArticleNo() {
		return this.articleNo;
	}

	public void setArticleNo(Integer articleNo) {
		this.articleNo = articleNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aId")
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@Column(name = "articleTitle", length = 50)
	public String getArticleTitle() {
		return this.articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	@Column(name = "article")
	public String getArticle() {
		return this.article;
	}

	public void setArticle(String article) {
		this.article = article;
	}

}
