package model.POJO;
// Generated 2019�~5��13�� �U��12:01:30 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivityMessage generated by hbm2java
 */
@Entity
@Table(name = "activityMessage", schema = "dbo", catalog = "final")
public class ActivityMessage implements java.io.Serializable {

	private Integer messageId;
	private Activity activity;
	private Member member;
	private String message;
	private Date messageTime;
	private Integer respondmessage;
	private Set<Report> reports = new HashSet<Report>(0);

	public ActivityMessage() {
	}

	public ActivityMessage(Activity activity, Member member, String message, Date messageTime, Integer respondmessage,
			Set<Report> reports) {
		this.activity = activity;
		this.member = member;
		this.message = message;
		this.messageTime = messageTime;
		this.respondmessage = respondmessage;
		this.reports = reports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "messageId", unique = true, nullable = false)
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aId")
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "email")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "message")
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "messageTime", length = 23)
	public Date getMessageTime() {
		return this.messageTime;
	}

	public void setMessageTime(Date messageTime) {
		this.messageTime = messageTime;
	}

	@Column(name = "respondmessage")
	public Integer getRespondmessage() {
		return this.respondmessage;
	}

	public void setRespondmessage(Integer respondmessage) {
		this.respondmessage = respondmessage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityMessage")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

}
