package model.POJO;
// Generated 2019�~5��13�� �U��12:01:30 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Friend generated by hbm2java
 */
@Entity
@Table(name = "friend", schema = "dbo", catalog = "final")
public class Friend implements java.io.Serializable {

	private Integer friendId;
	private Member memberByEmail1;
	private Member memberByEmail2;
	private String status;

	public Friend() {
	}

	public Friend(Member memberByEmail1, Member memberByEmail2, String status) {
		this.memberByEmail1 = memberByEmail1;
		this.memberByEmail2 = memberByEmail2;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "friendId", unique = true, nullable = false)
	public Integer getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Integer friendId) {
		this.friendId = friendId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "email1")
	public Member getMemberByEmail1() {
		return this.memberByEmail1;
	}

	public void setMemberByEmail1(Member memberByEmail1) {
		this.memberByEmail1 = memberByEmail1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "email2")
	public Member getMemberByEmail2() {
		return this.memberByEmail2;
	}

	public void setMemberByEmail2(Member memberByEmail2) {
		this.memberByEmail2 = memberByEmail2;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
