package model.POJO;
// Generated 2019�~5��13�� �U��12:01:30 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mail generated by hbm2java
 */
@Entity
@Table(name = "mail", schema = "dbo", catalog = "final")
public class Mail implements java.io.Serializable {

	private Integer mailNo;
	private Member memberByEmail1;
	private Member memberByEmail2;
	private String message;
	private Date deliveryTime;
	private String status;
	private String title;

	public Mail() {
	}

	public Mail(Member memberByEmail1, Member memberByEmail2, String message, Date deliveryTime, String status,
			String title) {
		this.memberByEmail1 = memberByEmail1;
		this.memberByEmail2 = memberByEmail2;
		this.message = message;
		this.deliveryTime = deliveryTime;
		this.status = status;
		this.title = title;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mailNo", unique = true, nullable = false)
	public Integer getMailNo() {
		return this.mailNo;
	}

	public void setMailNo(Integer mailNo) {
		this.mailNo = mailNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "email1")
	public Member getMemberByEmail1() {
		return this.memberByEmail1;
	}

	public void setMemberByEmail1(Member memberByEmail1) {
		this.memberByEmail1 = memberByEmail1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "email2")
	public Member getMemberByEmail2() {
		return this.memberByEmail2;
	}

	public void setMemberByEmail2(Member memberByEmail2) {
		this.memberByEmail2 = memberByEmail2;
	}

	@Column(name = "message")
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deliveryTime", length = 23)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
