package model.POJO;
// Generated 2019�~5��13�� �U��12:01:30 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "report", schema = "dbo", catalog = "final")
public class Report implements java.io.Serializable {

	private Integer reportId;
	private Activity activity;
	private ActivityMessage activityMessage;
	private Member memberByReportedEmail;
	private Member memberByReportEmail;
	private String content;
	private String type;
	private Date reportTime;
	private String status;
	private String response1;
	private String response2;
	private Date responseTime;

	public Report() {
	}

	public Report(Activity activity, ActivityMessage activityMessage, Member memberByReportedEmail,
			Member memberByReportEmail, String content, String type, Date reportTime, String status, String response1,
			String response2, Date responseTime) {
		this.activity = activity;
		this.activityMessage = activityMessage;
		this.memberByReportedEmail = memberByReportedEmail;
		this.memberByReportEmail = memberByReportEmail;
		this.content = content;
		this.type = type;
		this.reportTime = reportTime;
		this.status = status;
		this.response1 = response1;
		this.response2 = response2;
		this.responseTime = responseTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reportId", unique = true, nullable = false)
	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aId")
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "messageId")
	public ActivityMessage getActivityMessage() {
		return this.activityMessage;
	}

	public void setActivityMessage(ActivityMessage activityMessage) {
		this.activityMessage = activityMessage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reportedEmail")
	public Member getMemberByReportedEmail() {
		return this.memberByReportedEmail;
	}

	public void setMemberByReportedEmail(Member memberByReportedEmail) {
		this.memberByReportedEmail = memberByReportedEmail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reportEmail")
	public Member getMemberByReportEmail() {
		return this.memberByReportEmail;
	}

	public void setMemberByReportEmail(Member memberByReportEmail) {
		this.memberByReportEmail = memberByReportEmail;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "type", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reportTime", length = 23)
	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "response1")
	public String getResponse1() {
		return this.response1;
	}

	public void setResponse1(String response1) {
		this.response1 = response1;
	}

	@Column(name = "response2")
	public String getResponse2() {
		return this.response2;
	}

	public void setResponse2(String response2) {
		this.response2 = response2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "responseTime", length = 23)
	public Date getResponseTime() {
		return this.responseTime;
	}

	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

}
